# ========================================
# Core Settings
# ========================================
[core]
    editor = vim
    pager = delta
    attributesfile = ~/.config/git/attributes
    excludesfile = ~/.config/git/ignore
    autocrlf = input
    commentchar = ";"
    quotepath = false
    precomposeunicode = true
    untrackedCache = true
    fsmonitor = true

[pager]
    diff = delta
    log = delta
    reflog = delta
    show = delta

[interactive]
    diffFilter = delta --color-only

[http]
    postBuffer = 524288000

[credential]
    helper = osxkeychain
