# ========================================
# User Information
# ========================================

[user]
    name = Kazuyuki SUZUKI
    email = kechol@users.noreply.github.com
    signingkey = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMGNtnSYSY8A+Gw7gJbKWErRVXEbw6IdbDK+gFY3oNvv

[github]
    user = kechol

[ghq]
    root = ~/.ghq
