# ========================================
# User Information
# ========================================

[user]
    name = Kazuyuki SUZUKI
    email = kechol@users.noreply.github.com

[github]
    user = kechol

[ghq]
    root = ~/.ghq

